FROM python:3.9

WORKDIR /app
COPY Backend-main/requirements.txt /app/
RUN pip install -r requirements.txt

COPY Backend-main /app/Backend-main

EXPOSE 30

CMD ["python", "Backend-main/manage.py", "runserver", "0.0.0.0:30"]
