version: '3'

networks:
  my_network:
    driver: bridge

services:
  backend:
    container_name: backend
    networks:
      - my_network
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    command: sh -c "python Backend-main/manage.py runserver 0.0.0.0:30"
    ports:
      - "30:30"

  frontend:
    container_name: frontend
    networks:
      - my_network
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - backend
