FROM python:3.9

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        python3-dev \
        zlib1g-dev \
        libjpeg-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY Backend-main/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY Backend-main /app/Backend-main

EXPOSE 8080

CMD ["python", "Backend-main/manage.py", "runserver", "0.0.0.0:8080"]
