version: '3'

networks:
  my_network:
    driver: bridge

services:
  backend:
    container_name: backend
    networks:
      - my_network
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    command: sh -c "python Backend-main/manage.py migrate && python Backend-main/manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
